### ISSUE TITLE
amend awesome-fonts link

### ISSUE THREAD

**Issue by neeasade** [RizonRice/rizonrice.github.io#11]
Currently, bitmap-fonts and awesome-fonts both link to bitmap-fonts. 

https://rizonrice.github.io/resources#fonts

Where is the awesome-fonts link? most search results are just font awesome stuff.

**Comment by James-C-000** [comment]
I was unable to find any link that might be fitting of "awesome-fonts". Removed from list of fonts, but anyone is welcome to add it back if they find something for it.
