### ISSUE TITLE
"awesome" lists

### ISSUE THREAD

**Issue by DanielFGray** [RizonRice/rizonrice.github.io#22]
Making this issue to remind myself to add these

https://github.com/alebcay/awesome-shell
https://github.com/unixorn/awesome-zsh-plugins
https://github.com/fisherman/awesome-fish-shell

**Comment by azahi** [comment]
I'm a simple man. I see an open issue, I fix it...

**Comment by lwatsondev** [comment]
Fixed in 79e822e9e281b93b7e5400ff708837672a142705
